name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: "8.X"
      - name: install deps
        run: pnpm install
      - name: build app
        run: pnpm run build 
      - name: copy dist file with scp 
        uses: appleboy/scp-action@v0.0.1
        with:
          host: '119.3.180.124'
          username: 'nan'
          password: 'Lihaonan213.'
          port: 22,
          source: 'docs/'
          target: ''
